name: Host Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Move files to dist
        run: |
          mkdir -p dist
          cp -r install.lua dist/

      - name: upload files
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist
    
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
